version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755 # Read, write, execute for owner; read, execute for group and others

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
